services:
  front:
    image: emiliengibeaud/ecoride_front:latest
    container_name: ecoride
    labels:
      - "traefik.enable=true"
      # && !PathPrefix(`/ecoride/api`) évite un conflit de règle avec la stack ecoride_back
      - "traefik.http.routers.front.rule=Host(`petitmaraichin.myasustor.com`) && PathPrefix(`/ecoride`) && !PathPrefix(`/ecoride/api`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=myresolver"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      # Ajouts pour la stabilité
      - "traefik.http.services.front.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.front.loadbalancer.healthcheck.interval=30s"
    networks:
      - traefik_proxy
      - ecoride-network

networks:
  traefik_proxy:
    external: true
  ecoride-network:
    external: true
